[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false

[profile.default.optimizer_details]
peephole = true
inliner = true
jumpdestRemover = true

[profile.default.metadata]
bytecode_hash = "ipfs"

[profile.default.evm_version]
version = "paris"

[profile.default.gas_reports]
"*" = ["*"]

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "multi_line"
quote_style = "double"
number_underscore = "thousands"

[doc]
out = "docs"
out_dir = "docs"
